"""In-memory plan + idempotency store.

Plans generated by ``supervisor_plan`` are held here so that
``supervisor_execute`` can only act on a plan the user already reviewed.
Because Databricks Apps run stateless with ``stateless_http=True``, this store
is per-process and best-effort; a production deployment should back it with a
Delta/Lakebase table or a UC volume. It is adequate for the MVP, where plan and
confirmation happen in the same short-lived conversation.
"""

from __future__ import annotations

import threading
import uuid
from datetime import datetime, timezone

from .schemas import SupervisorGoal


class PlanStore:
    def __init__(self) -> None:
        self._plans: dict[str, tuple[SupervisorGoal, str]] = {}
        self._idempotency: dict[str, dict] = {}
        self._lock = threading.Lock()

    def put(self, goal: SupervisorGoal, expires_at: str) -> str:
        plan_id = f"plan_{uuid.uuid4().hex}"
        with self._lock:
            self._plans[plan_id] = (goal, expires_at)
        return plan_id

    def get(self, plan_id: str) -> SupervisorGoal | None:
        with self._lock:
            entry = self._plans.get(plan_id)
        if entry is None:
            return None
        goal, expires_at = entry
        if self._is_expired(expires_at):
            with self._lock:
                self._plans.pop(plan_id, None)
            return None
        return goal

    def consume(self, plan_id: str) -> None:
        with self._lock:
            self._plans.pop(plan_id, None)

    def seen_idempotency_key(self, key: str) -> dict | None:
        with self._lock:
            return self._idempotency.get(key)

    def record_idempotency(self, key: str, result: dict) -> None:
        with self._lock:
            self._idempotency[key] = result

    @staticmethod
    def _is_expired(expires_at: str) -> bool:
        try:
            exp = datetime.fromisoformat(expires_at.replace("Z", "+00:00"))
        except ValueError:
            return False
        return datetime.now(timezone.utc) >= exp


# Module-level singleton used by the tool functions.
plan_store = PlanStore()
